server:
  port: 8080
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://10.0.0.9:3306/linkdex
    username: skillbox_engine
    password: skillbox_engine
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: true
    hidden-method:
      filter:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
spring-doc:
  swagger-ui:
    path: /openapi
    operationsSorter: method
  writer-with-default-pretty-printer: true
app-configuration:
  userAgent: "Mozilla"
  referer: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36"
  siteList:
    - name: ""
      url: https://maxima.school
    - name: ""                      # if name is EMPTY AppConfig get title from main page
      url: https://u-house-sochi.ru
    - name: ""
      url: https://spaodissey.ru
    - name: ""
      url: https://andaseat.com
    - name: "Лента.ру"
      url: https://www.lenta.ru/
#    - name: "Плейбек"
#      url: http://www.playback.ru/
    - name: ""
      url: https://radiomv.ru/
#    - name: "ИПФ РАН"
#      url: https://ipfran.ru/
    - name: "НИКО АРТ"
      url: https://www.nikoartgallery.com/
#    - name: "Этсетра"
#      url: https://et-cetera.ru/
    - name: "Дом Булгакова"
      url: https://dombulsdfgakova.ru/




