server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: skillbox_engine
    password: skillbox_engine
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mvc:
    favicon:
      enabled: true
    hidden-method:
      filter:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
spring-doc:
  swagger-ui:
    path: /openapi
    operationsSorter: method
  writer-with-default-pretty-printer: true
app-configuration:
  userAgent: "Opera"
  referer: "https://www.yandex.ru"
  siteList:
    - name: ""
      url: https://maxima.school
    - name: ""                      # if name is EMPTY AppConfig get title from main page
      url: https://u-house-sochi.ru
    - name: ""
      url: https://spaodissey.ru
#    - name: ""
#      url: https://www.svetlovka.ru
    - name: ""
      url: https://andaseat.com
#    - url: http://www.playback.ru/
#      name: "Плейбек"
#    - url: https://volochek.life/
#      name: "Волочек"
#    - url: https://radiomv.ru/
#      name: "РадиоМВ"
#    - url: https://ipfran.ru/
#      name: "ИПФ РАН"
#    - url: https://dimonvideo.ru/
#      name: "Димон Видео"
#    - url: https://www.nikoartgallery.com/
#      name: "НИКО АРТ"
#    - url: https://et-cetera.ru/
#      name: "Этсетра"
    - url: https://www.lutherancathedral.ru/
      name: "Церковь"
    - url: https://dombulgakova.ru/
      name: "Дом Булгакова"
#    - url: https://www.svetlovka.ru/
#      name: "Светловка"



