spring:
  datasource:
    url: jdbc:mysql://v32:3306/search_engine
    username: skillbox_engine
    password: skillbox_engine
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mvc:
    favicon:
      enabled: true
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
app-configuration:
  site:
#    - name: "Учебный центр"
#      url: https://maxima.school/
    - name: "Дом в Сочи"
      url: https://u-house-sochi.ru
    - name: "Одисей"
      url: https://spaodissey.ru/
    - name: "Погода Яндекс"
      url: https://yandex.ru/pogoda
    - name: "Disk Яндекс"
      url: https://disk.yandex.ru/
    - name: "Яндекс Доставка"
      url: https://dostavka.yandex.ru



