spring:
  datasource:
    url: jdbc:mysql://v32:3306/search_engine
    username: skillbox_engine
    password: skillbox_engine
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: true
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
sites:
  site:
   - name: "Учебный центр"
     url: https://maxima.school/
   - name:  "Дом в Сочи"
     url: https://u-house-sochi.ru
#   - name: "Удаленный доступ"
#     url: https://getscreen.ru/
#   - name: "ФорСайт Компани"
#     url: https://forsite-company.ru

