spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: skillbox_engine
    password: skillbox_engine
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mvc:
    favicon:
      enabled: true
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
site:
  name: "Playback.ru"
  url: https://www.playback.ru
